### ISSUE TITLE
Delete all Data will delete everything in ~/Documents on Mac

### ISSUE THREAD

**Issue by adamwulf** [nathanborror/Heat#3]
😬 I've just found out that running this on the Mac → Delete all Data → will in fact delete _all_ data in ~/Documents, not just the data from this app...

Steps to repro:

1. Mac
2. build and run
3. open Preferences
4. Delete All Data
5. 😭

**Comment by nathanborror** [comment]
Oh no! I hope you have backups 🫣 Very sorry about this! I just pushed a fix that sandboxes the macOS app  (faa831b0d902baea012e9abd6372ed5d4ad2e461). I turned this off when I was experimenting with file system search. Thank you for bringing this to my attention.

**Comment by adamwulf** [comment]
Yep no worries, I do have a backup and was able to restore everything overnight. Thanks for the quick fix and for the very cool app!
